### ISSUE TITLE
Does not work under python 3.3

### ISSUE THREAD

**Issue by Krastanov** [concordusapps/pytest-bench#3]
Thanks for providing this tool. I had an issue when I tried to run it on python3.3:

```
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.3.2 -- pytest-2.3.5
plugins: cov, bench
collected 1 items 

test_eq.py .

----------------------------------------------------------------------------- benchmark session starts -----------------------------------------------------------------------------
collected 1 items

-------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                  Time (s)
-------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefan/rspcas/bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.3.5', 'console_scripts', 'py.test')()
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 493, in main
    exitstatus = config.hook.pytest_cmdline_main(config=config)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 441, in __call__
    return self._docall(methods, kwargs)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 452, in _docall
    res = mc.execute()
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 370, in execute
    res = method(**kwargs)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/main.py", line 109, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/main.py", line 103, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 441, in __call__
    return self._docall(methods, kwargs)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 452, in _docall
    res = mc.execute()
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 370, in execute
    res = method(**kwargs)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/terminal.py", line 337, in pytest_sessionfinish
    self.config.hook.pytest_terminal_summary(terminalreporter=self)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 441, in __call__
    return self._docall(methods, kwargs)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 452, in _docall
    res = mc.execute()
  File "/home/stefan/rspcas/lib/python3.3/site-packages/_pytest/core.py", line 370, in execute
    res = method(**kwargs)
  File "/home/stefan/rspcas/lib/python3.3/site-packages/pytest_bench/plugin.py", line 126, in pytest_terminal_summary
    name = benchmark.name
  File "/home/stefan/rspcas/lib/python3.3/site-packages/pytest_bench/plugin.py", line 37, in name
    self.item.cls.__name__,
AttributeError: 'NoneType' object has no attribute '__name__'

```

**Comment by mehcode** [comment]
Apologies for taking so long on this; I made some major changes to the tool. It seems to work under 3.3 for me. 

Can you try this again?

**Comment by Krastanov** [comment]
Thanks for the update! I will test it in the coming weeks. Given that you already have tested I guess I will close my issue for now.
